from solvers import lax_friedrich,lax_wendroff,kurganov_petrova,solve
from tests import do_convergence_test,do_smooth_convergence_test,do_conservation_test,do_total_variation_test
from plot import plot_solution

solvers=[lax_friedrich,lax_wendroff,kurganov_petrova]
do_convergence_test(solvers)
do_smooth_convergence_test(solvers)
do_conservation_test(solvers)
do_total_variation_test(solvers)
